theme: jekyll-theme-minimal  
title: HYF Be Homework Submission
description: Types of assignments, how to submit them, and what happens if you don not.  
logo: "https://user-images.githubusercontent.com/18554853/63941625-4c7c3d00-ca6c-11e9-9a76-8d5e3632fe70.jpg"
